version: '3.8'

services:
  backend:
    build: backend/
    restart: always
    depends_on:
      - db

# лучше по мигелю сделать правильно, а потом подкорректировать, а то пока не понятно, что важно, а что нет
  frontend:
    container_name: frontend
    build: ./
    restart: always
    ports:
      - "3000:80"

  db:
    image: postgres:15.3
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

#  nginx:
#    image: nginx:1.25
#    restart: unless-stopped
#    ports:
#      - 80:80
#    volumes:
#      - ./deployment/nginx:/etc/nginx/conf.d
