"""„mes“

Revision ID: aec1dbcfcfb7
Revises: 53e6605f53de
Create Date: 2023-07-14 07:22:39.294722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec1dbcfcfb7'
down_revision = '53e6605f53de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_products')
    op.drop_table('orders')
    op.drop_table('card_products')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_token')

    op.drop_table('users')
    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.drop_column('amount')

    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_token', ['token'], unique=False)

    op.create_table('card_products',
    sa.Column('card_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('card_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('card_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('card_image', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('card_id', name='card_products_pkey'),
    sa.UniqueConstraint('card_name', name='card_products_card_name_key')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.INTEGER(), server_default=sa.text("nextval('orders_order_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='orders_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('order_id', name='orders_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('order_products',
    sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='order_products_order_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name='order_products_pkey')
    )
    # ### end Alembic commands ###
